---
- name: VA Switch Cisco Outputs
  hosts: va
  gather_facts: false
  connection: network_cli

  tasks:
   - name: VA Switch Cisco Outputs
     cisco.ios.ios_command:
        commands: show run | exclude !Time
     register: output

   - name: Saving VA output to tmp
     copy:
       content: "{{output.stdout[0]}}"
       dest: "/home/hyellapragada/tmp/va-dc/{{inventory_hostname}}-config.txt"

- name: LA Switch Cisco Outputs
  hosts: la
  gather_facts: false
  connection: network_cli

  tasks:
   - name: Backup
     cisco.ios.ios_command:
        commands: show run | exclude !Time
     register: output

   - name: Saving LA output to tmp
     copy:
       content: "{{output.stdout[0]}}"
       dest: "/home/hyellapragada/tmp/la-dc/{{inventory_hostname}}-config.txt"

- name: EU Switch Cisco Outputs
  hosts: eu
  gather_facts: false
  connection: network_cli

  tasks:
   - name: Backup
     cisco.ios.ios_command:
        commands: show run | exclude !Time
     register: output

   - name: Saving EU output to tmp
     copy:
       content: "{{output.stdout[0]}}"
       dest: "/home/hyellapragada/tmp/eu-dc/{{inventory_hostname}}-config.txt"
