---
- name: Location1 Switch Cisco Outputs
  hosts: Location1
  gather_facts: false
  connection: network_cli

  tasks:
   - name: Location1 Switch Cisco Outputs
     cisco.ios.ios_command:
        commands: show run | exclude !Time
     register: output

   - name: Saving output to tmp
     copy:
       content: "{{output.stdout[0]}}"
       dest: "/home/<user>/tmp/Location1-dc/{{inventory_hostname}}-config.txt"

- name: Location2 Switch Cisco Outputs
  hosts: Location2
  gather_facts: false
  connection: network_cli

  tasks:
   - name: Backup
     cisco.ios.ios_command:
        commands: show run | exclude !Time
     register: output

   - name: Saving output to tmp
     copy:
       content: "{{output.stdout[0]}}"
       dest: "/home/<user>/tmp/Location2-dc/{{inventory_hostname}}-config.txt"

- name: Location3 Switch Cisco Outputs
  hosts: Location3
  gather_facts: false
  connection: network_cli

  tasks:
   - name: Backup
     cisco.ios.ios_command:
        commands: show run | exclude !Time
     register: output

   - name: Saving Location3 output to tmp
     copy:
       content: "{{output.stdout[0]}}"
       dest: "/home/<user>/tmp/Location3-dc/{{inventory_hostname}}-config.txt"
